### PR TITLE
Hypersistence Optimizer Issues: Blocker: PooledSequenceOptimizerEvent

### PR DESCRIPTION
**Pull request by ecruz165**

### CODE REVIEW

**Comment by chrisknoll** [comment]
Did you want to fold multiple changes to address Hypersistence Optimizer concerns into a single PR? I'm not sure if we're going to be fixing dozens or hundreds of messages (leading to the same number of PRs). Did you want to have this PR for issues of a certain severity (ie: critical and high?)

**Comment by ecruz165** [comment]
This was only one marked blocker. CLose out this PR. It is a same and easy one. 

The report pointed out 165 issues were found: 1 BLOCKER, 80 CRITICAL, 40 MAJOR, 44 MINOR. I'll review the critical and group a PR by type of issue raised.

**Comment by chrisknoll** [comment]
Ok, that's fine if this one covers all the 'blocker' category, we'll just leave the PR as-is and we'll merge it in as soon as we're done with our 2.13 release (which should be soon).

**Review by anthonysena — APPROVED** [review]

**Comment by alex-odysseus** [comment]
@ecruz165 @chrisknoll @anthonysena @wivern @anton-abushkevich @ssuvorov-fls 

Don't you find it risky to have the algorithm changed? Would it be possible that a new sequence generator algorithm will generate an identifier which already exists?

https://github.com/OHDSI/WebAPI/commit/1a114fa9d9798d93035abb2c7a0fe16a17082455 (I read that from Hibernate 5 the default value is "true" but we set it explicitly to "false")

**Comment by chrisknoll** [comment]
We marked it `false` in that commit because it messed with the 'implicit' auto generated columns in hibernate that we were using at the time.

Since then, we went to an explicit `sequence generator`, and so this option doesn't apply to us anymore.

**Pull request merged**
