### PR TITLE
Updates Hibernate to 5.4.2.FINAL.

### LINKED ISSUE #1081: Error creating cohort definition
### Actual result

Recieving an error: 
org.hibernate.id.IdentifierGenerationException: attempted to assign id from null one-to-one property [org.ohdsi.webapi.cohortdefinition.CohortDefinitionDetails.definition]

### Steps to reproduce
1. Create new cohort definition
2. Click save.  Observe 'error creating cohort definition'

### Code in question

```
  public CohortDTO createCohortDefinition(CohortDTO dto) {
    
      Date currentTime = Calendar.getInstance().getTime();

      UserEntity user = userRepository.findByLogin(security.getSubject());
      //create definition in 2 saves, first to get the generated ID for the new dto
      // then to associate the details with the definition
      CohortDefinition newDef = new CohortDefinition();
      newDef.setName(dto.getName())
              .setDescription(dto.getDescription())
              .setExpressionType(dto.getExpressionType());
      newDef.setCreatedBy(user);
      newDef.setCreatedDate(currentTime);

      newDef = this.cohortDefinitionRepository.save(newDef);

      // associate details
      CohortDefinitionDetails details = new CohortDefinitionDetails();
      details.setCohortDefinition(newDef)
              .setExpression(Utils.serialize(dto.getExpression()));

      newDef.setDetails(details);

      CohortDefinition createdDefinition = this.cohortDefinitionRepository.save(newDef);      <-- this results in the error described
      return conversionService.convert(createdDefinition, CohortDTO.class);
```

Oddly, the parent and child association (the cohort def is associated to the details, and the details are associated back to the cohort definition), but hibernate reports a NULL value in the one-to-one mapping.

### PR DESCRIPTION
**Pull request by chrisknoll**
Fixes #1081.

### CODE REVIEW

**Comment by chrisknoll** [comment]
@aklochkova , could you pull this branch and run your tests? I ran my own, and found that without making any code changes with detailsRepository, it saved the one-to-one mappings correctly.  I'd prefer moving up to a hibernate version that doesn't have the one-to-one mapping bug, so if this does work, let's go forward with this PR.

**Comment by aklochkova** [comment]
I can't save newly created Incidence Rate:
image

**Comment by chrisknoll** [comment]
Ok, I'm on it. thanks for checking.

**Comment by chrisknoll** [comment]
Ok, this should be fixed (at least on MSSQL), can you check your own ENV?

**Comment by aklochkova** [comment]
Yes, it's working now

**Comment by chrisknoll** [comment]
Great, could you apply your approval on this PR? I'll get it merged in.

**Pull request merged**
