### PR TITLE
Datasources Expansion and Improved Speed

### PR DESCRIPTION
**Pull request by lhalvors**
Implements features requested in issue #227 
- adds new Frequency Distribution graph in DataSources
- improvement of DataSources performance, by using a concept_hierarchy table generated by Achilles

### CODE REVIEW

**Comment by chrisknoll** [comment]
@lhalvors , it looks like your updates were done prior to some of the changes related to removing quoted identifiers out of the sql templates. Could you resolve the conflicts?

**Comment by anthonysena** [comment]
@chrisknoll - I've made some updates to this branch from @lhalvors to resolve the conflicts. I've also done some work on OHDSI/Atlas#471 to update the code for compatibility with D3 v4. Since this work was originally done in a fork and not a branch, would it be best to merge this into a feature branch on each respective repository so I can contribute those changes?

**Comment by chrisknoll** [comment]
If you want to take his PR and run with it, I would suggest creating a branch in the OHDSI/WebAPI repo and then editing this PR to target that new branch instead of the current target of 'master'. then you can check it out, commit, and make any change you require. this means, however, that they won't have direct commit rights to that branch so you're taking the ball and running with it if you choose that approach.  

If that's what you intended to do anyway, then I fully agree :)  I understand the challenge of working across repos like that. Do what works the best, and we can always clean it up in the final PR branch.

**Comment by anthonysena** [comment]
Thanks @chrisknoll - that's exactly what I had in mind. @lhalvors let me know if you have any concerns with this approach. I'll look to do this work tomorrow.

**Comment by lhalvors** [comment]
Thanks @anthonysena , I'm fine with this approach. Please let me know what actions or steps I can do.

**Pull request merged**
