### PR TITLE
Enable PC and DPC for source and non-standard concepts

### PR DESCRIPTION
**Pull request by TomWhite-MedStar**
This, in combination with a pull request # [721 ](https://github.com/OHDSI/Achilles/pull/721)for Achilles, 
It solves the issue discussed in [this](https://forums.ohdsi.org/t/patient-counts-on-non-standard-concepts/18143/6) forum post.
I confirmed that this works on my Databricks instance.

### CODE REVIEW

**Comment by TomWhite-MedStar** [comment]
@chrisknoll , per discussion, removed Achilles analysis # 40

**Comment by anthonysena** [comment]
Thanks @TomWhite-MedStar for this contribution! I'd like to wait and see the outcome of OHDSI/Achilles#721. Assuming that is approved and the analyses you've added are included, we'll be able to merge this into WebAPI.

**Comment by TomWhite-MedStar** [comment]
Thanks.  @anthonysena , or @chrisknoll , Do you need any more information from me about [OHDSI/Achilles#721](https://github.com/OHDSI/Achilles/pull/721)?

**Comment by anthonysena** [comment]
I think we're set on the WebAPI side @TomWhite-MedStar. I just want to make sure that the analysis IDs referenced in the WebAPI query are the ones that are finalized in Achilles. I know that we could merge this in now but in the off-chance that the Achilles folks have any desire to change analysis IDs for some reason, we'd have to patch this up.

**Comment by chrisknoll** [comment]
I think it'll be a low priority that they will object to the analysis_ids so how about we accept it here with that slight risk, and if they do change the analysis_ids, we can patch.

**Comment by anthonysena** [comment]
That's good by me thanks @chrisknoll

**Review by chrisknoll — APPROVED** [review]

**Pull request merged**
