### PR TITLE
Fixes #108

### LINKED ISSUE #108: Add summary service
Enhance WebAPI so that it features a summarization/characterization service. The proposed service would accept requests for and respond with data directly from the Achilles results table, rather than from the Achilles-exported JSON files. The data from the service could then be used to populate the visualizations in Atlas (Datasources).

This issue is potentially part of the Achilles integration effort that may subsume issue #49.

### PR DESCRIPTION
**Pull request by t-abdul-basser**
Fixes #108. This PR would introduce enhancements to CDMResultsService and related classes so that consumers (such as Atlas) to request and receive Achilles-generated results. It is meant to be an alternative to exported JSON files.

### CODE REVIEW

**Comment by chrisknoll** [comment]
@t-abdul-basser , @mark-velez:

Thanks for your work on this, but I have 2 concerns:

1. There's 79 commits in this branch that I think should be squelched (but this could be done at merge time, however doing so could help with point 2)
2. It looks like a lot of the lines of code change is related  to formatting. We should keep those kinds of changes to a minimum.

I think it is advisable that you squelch the changes into 1 or two commits, and then you can use a DIFF tool between the commits to identify which lines were changed merely from formatting.  Any set of changes you see that were just formatting changes, you can use the prior version to copy the prior-formatted block of code into your branch to remove those changed lines.

Here's how I'd do this (first making sure your remote references are updated using git fetch):

1. do a git checkout achilles-integration-generic (to set current branch to your PR branch)
2. do git branch -b achilles-integration-pr (this will create a branch pointer right on top of your integration branch)
3. do git rebase -i HEAD~79 (for the 79 commits in this PR) or:
3. do git merge-base git achilles-integration-pr origin/master and then using that hash do git rebase -i ${hash} (replace ${hash} with the value from the merge-base command)
4. The git rebase -i command will bring up a list of commits that you can edit the file to change the 'pick' rows to 'squash' rows (first row will be pick, subsequent rows will be 'squash').

Save and close the rebase editor and it will squash everything down.  You shouldn't run into any conflict errors because you are just rebasing the -pr branch right on top of the commit you created your branch from.  And you don't need to worry about impacting your _achilles-integration-generic_ branch, the rebase command is only going to mess with the -pr branch, you can always go back to the -generic branch.

There's a great guide on this here; https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request

Important thing to note is: this -pr branch you created is going to be your own local branch, so you can do whatever you want with it to clean it up.  After you rebase it down to 1 squash, you can compare that commit to the version in master to see which changes was from just a formatting change vs. changes that are new code.  Any blocks of changes you see that are just formattting, just copy from the prior version into the current version and then that block of code won't look changed anymore.  Use git commit --amend to put your cleanup changes directly into the squashed commit you made from your rebase. Again, don't worry about 'rebasing history' here because your working on a whole new branch and you can do whatever you like to clean it up.

Finally, when all of this is squelched down and the changes are limited to the changes related for this PR,  you can git push the branch and create a new PR based off the -pr branch and close the PR that is based off of the -generic branch.

Let me know if you need any help!

-Chris

**Comment by t-abdul-basser** [comment]
Yes. I could have rebased (interactively) and squashed myself via the command line but wanted to use the GitHub support to do that within the context of the PR. (GitHib support in-PR-context squashing and rebasing). If we would feel more comfortable doing this via the `classic` method, I can certainly. I will address this and modify/reissue as needed. Thanks.

**Comment by anthonysena** [comment]
@t-abdul-basser will there be a corresponding PR for Atlas that leverages these WebAPI enhancements? Just wanted to inquire since I'd want to test these together. My other reason for asking: we've got a lot of merging work to do for Atlas and I want to make sure we account for any companion changes to this PR.

Thanks!

**Comment by t-abdul-basser** [comment]
@anthonysena Yes. @mark-velez will issue that shortly. He and @fdefalco agreed to work together given the other branch that the latter mentioned in our last Architecture call.

**Comment by chrisknoll** [comment]
Hey @t-abdul-basser, I only was suggesting the pre-merge rebase so that it would be easier to clean up the formatting related changes that were put into the PR.

**Comment by t-abdul-basser** [comment]
You are of course absolutely right: it only decent to clean things up to make things easier on you as reviewers :) I typically do that but will squash, reword; rebase and re-issue shortly. Thanks!

**Comment by chrisknoll** [comment]
Thanks very much for your consideration.

**Pull request closed without merging**
