### PR TITLE
Update pom.xml - #1708

### PR DESCRIPTION
**Pull request by anthonysena**
Per #1708, updating the components that are either released or have a snapshot version available. For this PR, I'd propose that we merge this into master for testing but leave #1708 open so we can track the remaining work to test with the latest versions of all components and ultimately release them to the nexus repo.

### CODE REVIEW

**Comment by chrisknoll** [comment]
I don't foresee any additional circe-be changes prior to 2.8, did you want me to deploy a 1.9.0 release and we can update the pom.xml for that dependency inside this release?

**Comment by anthonysena** [comment]
Hi @chrisknoll - sure that would be great.

**Comment by anthonysena** [comment]
From discussion internal discussion: 

- Use Hydra v0.0.11 vs v0.1.1 as this will have impact on Arachne and address in 2.8.x
- Use FeatureExtraction v3.1.0 and if defects found, roll back to v2.2.5 
- @chrisknoll will release v1.9.0 of circe-be. One this is set, @anton-abushkevich will release the StdApi & SkeletonCC components.

**Comment by chrisknoll** [comment]
Just an update, circe-be depends on StdAPI, so I will ask them to publish that release, I will update circe to point to released dependencies, and then release circe-be for SkelCC (which depends on circe).

Dependency graphs are fun :)

**Comment by chrisknoll** [comment]
standard-analysis-utils (1.3.0), standard-analysis-specs (1.3.0) and circe (1.9.0) have been released, if you'd like to update the pom in this PR.

**Comment by anthonysena** [comment]
We should merge in this commit: 5a0ea03c15034e65807f604ae2c44fa089f8bbdb to master to update the pom.xml reference.

**Comment by anthonysena** [comment]
Closing since https://github.com/OHDSI/WebAPI/commit/5a0ea03c15034e65807f604ae2c44fa089f8bbdb covers it.

**Pull request closed without merging**
