### PR TITLE
Update getCohortAnalysesForCohort.sql

### PR DESCRIPTION
**Pull request by evillalonNY**
It does not work without the CAST in SQL Server

### CODE REVIEW

**Comment by cahilton** [comment]
This is a duplicate pull request - I already submitted a pull request, it just hadn't bene merged.

**Comment by evillalonNY** [comment]
Thanks I did not know. Best Elena
________________________________

**Comment by cahilton** [comment]
Oh no worries at all. I just wanted others to review it, but I can go ahead and merge it if it looks good for SQL server. It includes one other change requested for SQL Server.

**Comment by fdefalco** [comment]
Accepting original pull request.

**Pull request closed without merging**
