### PR TITLE
Add source seq for sqlserver...

### PR DESCRIPTION
**Pull request by NEONKID**
@chrisknoll I have confirmed the overlapped part of PR. So I worked on the name of another branch and removed the part already applied. (Continuous #795)

### CODE REVIEW

**Comment by chrisknoll** [comment]
Did you also have scripts for postgresql and oracle for this?

**Comment by NEONKID** [comment]
@chrisknoll I added queries for PostgreSQL and Oracle, but I could not test it because I found it difficult to get PostgreSQL and Oracle to where I was.

Could you run the test?

**Comment by chrisknoll** [comment]
Great! let me pull this down and get this reviewed. Thanks for the quick turnaround.

**Comment by pavgra** [comment]
Since this PR is fork-based and we cannot add commits to it, I'm going to merge this first and then merge https://github.com/OHDSI/WebAPI/pull/816

**Pull request merged**
