### PR TITLE
Added Location Region analyses to CC

### PR DESCRIPTION
**Pull request by pavgra**
image

### CODE REVIEW

**Comment by anthonysena** [comment]
@pavgra can you link this to an existing issue or open a new one?

**Comment by pavgra** [comment]
Related to https://github.com/OHDSI/WebAPI/issues/649

**Comment by anthonysena** [comment]
From discussion with @pavgra and @gklebanov, I'm moving this to the 3.0 milestone since these changes utilize CDM 6.x functionality.

**Comment by alondhe** [comment]
@anthonysena -- this looks like work that could be really useful; we're starting to need more location-based analytics. If we were to refactor it to work with CDM 5.3 / 5.4, do you think that'd be also useful for others?

**Comment by anthonysena** [comment]
@alondhe - we made this PR a draft since it required tables in CDM v6.0 (specifically `location_history` but there may be others I'm missing). I'm not sure how easily this is ported to CDM v5.3/v5.4 but you could attempt to create some custom feature, as was done in this PR, to try it out in your environment.

**Pull request closed without merging**
