### PR TITLE
Issue #217 and #223

### PR DESCRIPTION
**Pull request by chen-regen**
@anthonysena , please review. Thank you!

### CODE REVIEW

**Comment by anthonysena** [comment]
Hi Chen - thanks for submitting this PR along with the OHDSI/Atlas#432 PR. 

Could you rebase your R21 branches in both repos off of their respective master branches? I ask since there are a few commits in both PRs that are already in master and there are some conflicts that should be resolved before we review these changes. Just reach out if you have any questions. Thanks!

**Comment by chen-regen** [comment]
@anthonysena , I just did rebase on both WebAPI and Atlas.

**Comment by anthonysena** [comment]
Thanks Chen - appreciate the update here. I'll plan to do a review next week and will reach out with any questions.

**Comment by anthonysena** [comment]
Replaced by #230

**Pull request closed without merging**
