### PR TITLE
Sequences for entities

### PR DESCRIPTION
**Pull request by wivern**
for #324

### CODE REVIEW

**Comment by chrisknoll** [comment]
This looks very impressive, and I like how you worked through all the 'initial values for sequences'.  The oracle code looks pretty complicated and I don't actually have any way of testing this out.

It appears that you put in the various checks for when max(id) might return null, which is good, this migration needs to work when the database is empty (such as in a completely new install).  Did you manage to test this migration on the different flavors of RDBMS?  We can test the migrations internally on MSSQL and Postgresql (@anthonysena : you have a local install of Postgresql with some cohort defs?) but oracle has always been a challenge. If you can confirm that this works for Oracle, we'll work out testing it on the other 2 platforms.

**Note to everyone: before running webapi with this PR in place, I strongly suggest making a backup of your database before launching.  The changes here are not easily rolled back, so your best option is a backup-restore if something doesn't work right.**

**Comment by anthonysena** [comment]
I can test this out on PostgreSQL.

+1 for backing up your DB!

**Comment by chrisknoll** [comment]
Ok, I'll check it on our internal SQL server.  @chen-regen : do you have an oracle instance you could test this with?

**Comment by anthonysena** [comment]
@chrisknoll - This is my bug - sorry for that. I contributed that script as part of another PR. Let's change it since we should assume that a previous script created those columns and therefore the existence check is not required. 

Also, for all: I'm also finding some bugs with the PostgreSQL script for sequencing. I'm thinking it might be easier to merge this working into a branch on WebAPI so that we can all contribute fixes on it? I'll plan to do this unless I hear from folks not to do that.

**Comment by chen-regen** [comment]
@chrisknoll @anthonysena  Hi Anthony and Chris, sorry I just noticed this as Anthony brought it to my attention. I am actually working on a solution for the sec_role_permission table by sequence. Regenstrief will be working on creating a second instance for our OHDSI suite. Now we only have one instance so it would be challenging and dangerous for me to test this big changes. When do we plan on getting this released? I will try to talk to our folks here and see if we can get a testing environment sooner...

**Comment by anthonysena** [comment]
Hi @chen-regen - we aim to have the 2.3 release ready by 2/28 per #301. I'd agree that it is important to have a secondary environment for testing these changes. Just let us know the timing for your secondary environment and worst case, we can apply some patches as part of a 2.3.x release to address any issues found with Oracle.

**Comment by chen-regen** [comment]
@anthonysena wow this is pretty intense in terms of timing. I doubt our infrustracture team will get the environment ready by then considering they are working on our new ARACHNE servers now. Well if I won't be able to test, we will have to apply patches as you said. Internally, we really would like to get the cohort analysis changes and security improvements deployed with 2.3 release...

**Pull request merged**
