### PR TITLE
Fixed getting a keytabPath

### PR DESCRIPTION
**Pull request by aklochkova**

### CODE REVIEW

**Comment by JamesSWiggins** [comment]
This commit produces the following error for me when compiling:

[INFO] Compiling 687 source files to /tmp/WebAPI/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /tmp/WebAPI/src/main/java/org/ohdsi/webapi/service/AbstractDaoService.java:[180,37] error: cannot find symbol
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE

**Comment by pavgra** [comment]
@JamesSWiggins , could you show, how your line 180 of `AbstractDaoService.java` looks like?

**Comment by JamesSWiggins** [comment]
Pulled from v2.6.0 branch:
WebAPI/src/main/java/org/ohdsi/webapi/service/AbstractDaoService.java:[180]
FileUtils.forceDelete(krbConfig.getKeytabPath().toFile());

**Comment by JamesSWiggins** [comment]
Oh, it seems like one of these commits fixes that issue.  Can it be merged into the latest release branch?

**Comment by pavgra** [comment]
@JamesSWiggins , I've updated `v2.6.0` tag to fix the issue

**Pull request merged**
