### PR TITLE
Allow to skip connection check for certain sources

### PR DESCRIPTION
**Pull request by ganisimov**
Addresses #2359

### CODE REVIEW

**Review by chrisknoll — APPROVED** [review]
Looks good. Is there any other modifications you would want to make before we merge this PR?

**Comment by ganisimov** [comment]
@chrisknoll , the checkConnection() is used in API call /source/connection/{key} here:
https://github.com/OHDSI/WebAPI/blob/6a43da50ab2bf10df18306df658933ec6a49235e/src/main/java/org/ohdsi/webapi/source/SourceController.java#L348
So, I'm not sure if it's desired to suppress connection check here in any case. If the change was requested to optionally skip the check only when dealing with daimons (#2350), I would handle the setting closer to that code and not in checkConnection(). Do you have any thoughts on this?

**Comment by chrisknoll** [comment]
Seems like if the setting on the source is to disable check connections, then it's reasonable that all calls to check connection will just bypass.  So, in the case you show here, you would want to bypass the check in all cases.

**Comment by ganisimov** [comment]
OK then I'm good with the changes, thanks!

**Pull request merged**
