### PR TITLE
remove quotes around alias names in cdmresults report sql

### PR DESCRIPTION
**Pull request by gowthamrao**
Refers to issue #237

### CODE REVIEW

**Comment by gowthamrao** [comment]
@chrisknoll

**Comment by chrisknoll** [comment]
Hi, @gowthamrao , I think @t-abdul-basser would be better to review the updates you've suggested since it involves the database characterization function of webapi.

**Comment by t-abdul-basser** [comment]
Thanks @chrisknoll.

Thanks for the submission @gowthamrao. @mark-velez or I will review.

**Comment by gowthamrao** [comment]
@t-abdul-basser @chrisknoll does this need to be merged?

**Comment by t-abdul-basser** [comment]
Thanks @chrisknoll!

**Pull request merged**
