### PR TITLE
Fixing IR generation at Impala

### PR DESCRIPTION
**Pull request by pavgra**
Fixes https://github.com/OHDSI/WebAPI/issues/413

### CODE REVIEW

**Comment by wivern** [comment]
There are not enough changes to make Impala work.
The issue is that SqlRender is ignored since PreparedStatementRender got null instead of actual Source.

**Comment by chrisknoll** [comment]
By the way, @wivern  and @pavgra , There is a method on PreparedStatementRenderer to set the targetDialect directly (via setTargetDialect(), and so if you didn't want to make a 'fake' source instance, you can pass null as the source, and later call setTargetDialect().

**Comment by chrisknoll** [comment]
@wivern:  when you merge the PRs, can you please use 'rebase and merge' if the PR commits look meaningful, or just 'squash and merge' to combine all commits into a single commit into master. We'd like to keep the commit history on master as clean as possible. 

Thank you!

**Comment by pavgra** [comment]
@chrisknoll , @wivern , the code block uses `getSql()`, which is just getter of the `sql` field of the PreparedStatementRenderer. The `sql` field is calculated in constructor, where `SqlTranslate` is used based on the `source` param. `setTargetDialect` doesn't affect the `sql` anyhow and the constructor is the only place where `SqlTranslate` is applied

**Comment by chrisknoll** [comment]
Thanks @pavgra , as usual you are correct :)  But that's a flaw in the PSR that should be addressed:  there's no way to use the target dialect for anything. I'll work on a PR for this.

**Pull request merged**
