### PR TITLE
Sqlrender sessionid

### PR DESCRIPTION
**Pull request by alexfranken**
This pull is dependent upon SqlRender branch and getting Jenkins to push out snapshots to nexus.  Wanted to submit this now so that review can happen.  Curious if anyone has any thoughts to the simple sessionId implemented.  Current implementation produces a unique global temp table for each call, which made sense because WebAPI is stateless in nature.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Looks good,  I was thinking about a time based number genterator, but if we go with parallel processing it's possible that 2 threads could get the same time index on different cores. So a random character string generator seems safe.

**Comment by leeevans** [comment]
Alex, I've now setup the Jenkins build job for SqlRender so it automatically builds when SqlRender code is updated on GitHub.  The Jenkins build job also pushes SqlRender snapshots to the OHDSI Nexus maven repo.

**Comment by cahilton** [comment]
Have we made any resolution towards merging this? We're starting to run some Heracles jobs (not just me) and it may become a necessity.

**Comment by alexfranken** [comment]
I will follow up with martijn

**Comment by alexfranken** [comment]
Looks like Martijn merged in the changes. I  will have to review the conflicts before this can be merged. Will try to do thus weekend or Monday.

**Comment by cahilton** [comment]
Thanks Alex. Since I deployed Heracles out there, I'm afraid we'll have people wanting to use it already. Jon showed it to Faye, and her group will probably want to be hitting it soon.

**Comment by alexfranken** [comment]
@cahilton , I've updated this branch.  However, it is failing because the jdbc statements are trying to use the heracles_cohort table without the global temp table prefix.  Doesn't look like this script has changed recently... Maybe it's a bug introduced in the SqlRender snapshot...  Going to call it a night...
```
2015-03-13 22:46:16.322 DEBUG http-nio-8080-exec-1 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 0 : ALTER SESSION SET current_schema =  AFRANKEN
2015-03-13 22:46:16.322 DEBUG http-nio-8080-exec-1 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 1 : delete from AFRANKEN.HERACLES_results where cohort_definition_id IN (1) and analysis_id IN (1,2,1800,1801,1802)
2015-03-13 22:46:16.322 DEBUG http-nio-8080-exec-1 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 2 : delete from AFRANKEN.HERACLES_results_dist where cohort_definition_id IN (1) and analysis_id IN (1,2,1800,1801,1802)
2015-03-13 22:46:16.322 DEBUG http-nio-8080-exec-1 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 3 : BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE  HERACLES_cohort';
  EXECUTE IMMEDIATE 'DROP TABLE  HERACLES_cohort';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
2015-03-13 22:46:16.323 DEBUG http-nio-8080-exec-1 org.ohdsi.webapi.service.CohortAnalysisService -  - Split SQL 4 : BEGIN
  EXECUTE IMMEDIATE 'TRUNCATE TABLE  AFRANKEN.kwk57q5nHERACLES_cohort';
  EXECUTE IMMEDIATE 'DROP TABLE  AFRANKEN.kwk57q5nHERACLES_cohort';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
```

**Comment by schuemie** [comment]
The last command did include the prefix, but the one before that didn't. Is there any way to find out what the SQL was before translation?

**Comment by alexfranken** [comment]
I believe we are translating the following file... https://github.com/OHDSI/WebAPI/blob/master/src/main/resources/resources/cohortanalysis/sql/runHeraclesAnalyses.sql

**Comment by schuemie** [comment]
Ah, there were some statements that were already obsolete, and now actively harmful. I removed them in bf774202e65cd36f7ee3e9e428b06d13249d1269

**Comment by alexfranken** [comment]
Thanks @schuemie I'm proceeding with the merge.

**Pull request merged**
