### PR TITLE
JPA + Spring Data - Initial Support

### PR DESCRIPTION
**Pull request by alexfranken**
Notes:
* This branch was based on the flyway branch.
* This branch, at time of writing, can automatically merge with master so I have not yet added the merge commit to catch up my branch.  I can do that if preferred.
* Use TransactionTemplate (`getTransactionTemplate()` in AbstractDAOService or `@Autowired TransactionTemplate transactionTemplate` for spring managed beans (e.g. Tasklets).
** Changed CohortAnalysisTasklet to use TransactionTemplate
* Added flyway migration script for JPA 'HIBERNATE_SEQUENCE' (oracle, sql server, postgres)
* Reference ExampleApplicationWithJobService class & WidgetRepository - example endpoints `GET example/widget` or `POST example/widget --data "{name:'John Doe'}"
* Disabled connection pooling (due to http://forums.ohdsi.org/t/transaction-vs-session-scope-for-global-temp-tables-statements/333/2 )
** With this, validationQuery is unnecessary.  Consider validatorClass or sql template for validation query when pooling is enabled.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Ok, so how should we do this? Do we need to merge in flyaway first?  I haven't been able to try it out yet, but if there's no alternative, then it probably doesn't matter.

**Comment by alexfranken** [comment]
You can ignore the flyway branch and review this branch. 
Example profile for settings.xml
```
		<profile>
			<id>webapi-sqlserver</id>
			<properties>
				<datasource.dialect>sql server</datasource.dialect>
				<datasource.cdm.schema>[CDM_DATABASE].dbo</datasource.cdm.schema>
				<datasource.ohdsi.schema>[CDM_DATABASE_RESULTS].dbo</datasource.ohdsi.schema>
				<datasource.dialect.source>sql server</datasource.dialect.source>
				<datasource.url>jdbc:sqlserver://serverName</datasource.url>
				<datasource.username>x</datasource.username>
				<datasource.password>y</datasource.password>
				<flyway.datasource.url>jdbc:sqlserver://serverName</flyway.datasource.url>
				<flyway.datasource.username>ohdsiResultsUserWithWriteAccess</flyway.datasource.username>
				<flyway.datasource.password>x</flyway.datasource.password>
				<flyway.locations>classpath:db/migration/sqlserver</flyway.locations>
				<!-- Note: Schema name is case-sensitive. -->
				<flyway.schemas>${datasource.ohdsi.schema}</flyway.schemas>
			</properties>
		</profile>
```
If using sqlserver, you won't have to modify the flyway.locations, and as long as you have datasource.ohdsi.schema defined, you can leave flyway.schemas alone.

Let me know if you have any questions.  I haven't run it against any other databases yet, so let me know if you run into any problems.

**Comment by alexfranken** [comment]
I should also say that if you prefer to look at flyway first and make a decision, that is fine.  Then, if I need to pull out Flyway support, I can do that and we can then consider this branch.  Options...

**Comment by leeevans** [comment]
Hi Alex,

I see you are updating the SQL Server (default) and webapi-oracle profile when adding new Spring properties to pom.xml which is great.  Please also add any new Spring properties to the webapi-postgresql profile.  The webapi-postgresql profile is used by the Jenkins CI build so it needs to be maintained to avoid breaking the CI build.

Thanks in advance,
Lee

**Comment by chrisknoll** [comment]
Hi Alex.  I'll just look in on this branch, since if you don't have any reservations with Flyway then you're in the best position to decide if it's workable or not.  I'd just like to get it set up in my own enviornment and understand the configuration of it. Your example settings.xml is extremely helpful. thank you!

I'm sure I'll have questions about what it takes to get the JPA stuff situated too, but I'll just focus on getting flyway working for now.

-Chris

**Comment by alexfranken** [comment]
@leeevans , I pushed up a more complete set of key properties for the postgresql profile.  I've included the below profile if you're using settings.xml.  This list is pretty much comprehensive, including all properties for clarity, regardless if the default properties would have worked.
Are you using settings.xml or java arguments to override defaults (i.e. mvn -Ddatasource.password=)?
Take special note that the username/password is not included in the url any longer.
Take special note that the datasource.ohdsi.schema is correct (case sensitive).  This is the schema flyway will manage.  User/pass need write access.
Take special note of the flyway.datasource.username & flyway.datasource.password props as these need to be valid.  In theory it should be a different user but doesn't have to be as long as write access is enabled.  Let me know if you run in to any snags and any error messages that may occur.
```
		<profile>
			<id>webapi-postgresql</id>
			<properties>
				<datasource.driverClassName>org.postgresql.Driver</datasource.driverClassName>
				<datasource.url>jdbc:postgresql://54.209.111.128:5432/vocabularyv5</datasource.url>
				<datasource.username>USER</datasource.username>
				<datasource.password>PASS</datasource.password>
				<datasource.dialect>postgresql</datasource.dialect>
				<datasource.cdm.schema>unrestricted</datasource.cdm.schema>
				<datasource.ohdsi.schema>ohdsi</datasource.ohdsi.schema>
				<datasource.cohort.schema>ohdsi</datasource.cohort.schema>
				<flyway.datasource.driverClassName>${datasource.driverClassName}</flyway.datasource.driverClassName>
				<flyway.datasource.url>${datasource.url}</flyway.datasource.url>
				<flyway.datasource.username>userWithWritesToOhdsiSchema</flyway.datasource.username>
				<flyway.datasource.password>PASS</flyway.datasource.password>
				<flyway.locations>classpath:db/migration/postgresql</flyway.locations>
				<!-- Note: Schema name is case-sensitive. -->
				<flyway.schemas>${datasource.ohdsi.schema}</flyway.schemas>
			</properties>
		</profile>
```
@chrisknoll - I think flyway is very valuable. In fact, I'll probably start rolling it out to other projects.  The inconvenience for this project, is creating scripts for each supported database platform.  I only added scripts for oracle, sqlserver, & postgres.  What is the official supported list?

**Comment by chrisknoll** [comment]
mssql, oracle, postgres, redshift. Someone is working on getting translations for Netiza (sp?).  I agree it's painful, but hopefully just a 'one shot' deal (per db change), and maybe we can even find a DDL translator that will make it easier for us.  But I'm defiantly liking the flexibility it offers.

Tomorrow I'll get this JPA branch local and hopefully get up to speed on how it operates.  Save/load cohort definitions is the next thing on my list.

**Comment by leeevans** [comment]
Hi Alex, thanks for updating the webapi-postgresql profile.  I'm using settings.xml in the CI server build.  I'll let you know if we get any build errors that require source code/pom.xml changes but other than that I'll endeavor to update setttings.xml and the postgresql database DDL/permissions as needed.

**Comment by chrisknoll** [comment]
I just made a push to this pull request to add a separate cdmDatabase property for environments that have a cdm database in a separate database name from the ohdsi results.  For those in MSSql land, this means that the cdmSchema and ohdsiSchema should be set to dbo, the cdmDatabaseName should be set to the name of the database that contains the CDM tables, and in the jdbc url, you should specify the database name of the results database as such:
jdbc:sqlserver://serverName;databaseName=databaseName

I tested the flyway table creation with a 'widget' JPA entity and the spring batch tables, and in my environment I had to specify the schema as 'dbo' (formerly it was {database}.dbo).  For oracle, I believe you will be able to leave the pom.xml (or settings.xml) property for database name to just <datasource.cdm.database /> (which is the default in the pom.xml).

**Comment by chrisknoll** [comment]
If no one can find an issue related to this push, could Frank, Alex or Charity please merge and close this pull request?

Also, I found this url that could help us with converting DDL across platforms:
http://www.sqlines.com/online

Seems to support all the platforms that we need, although it is manual (in that you have to paste your DDL for your platform and copy out the translated form into another migration folder).

**Comment by alexfranken** [comment]
I'd prefer not to merge my own pull request so I'll defer to others...

**Pull request merged**
