### PR TITLE
Set job status to failed when exception is thrown in listener.

### LINKED ISSUE #2216: CohortGeneration job left in 'STARTED' state when error is thrown.
### Expected behavior
If there is a failure during cohort generation, the job should result in FAILED.

### Actual behavior
The exception thrown in GenerationJobExecutionListener is ignored by Spring Batch.

### Steps to reproduce behavior

This is difficult to reproduce because you need to throw an exception during `GenerationJobExecutionListener.findBySourceId`.
However, the behavior is described [here](https://stackoverflow.com/questions/48210366/can-an-exception-in-a-spring-batch-listener-cause-the-job-to-fail).

The solution is to wrap the work done in afterJob (which contains the call to findBySourceId) in an exception handler such that the job step is set to failed:

Example code:
```
public class YourListener implements StepExecutionListener {

    @Override
    public ExitStatus afterStep(StepExecution stepExecution) {
        try {
            yourcode ///////
        } catch (Exception e) {

            //log your error 
            stepExecution.setStatus(BatchStatus.FAILED);
            stepExecution.addFailureException(e);
            return ExistStatus.FAILED.addDescription(e);
        }
        return ExitStatus.COMPLETED;
    }
}
```

### PR DESCRIPTION
**Pull request by chrisknoll**
Fixes #2216.

### CODE REVIEW

**Comment by alex-odysseus** [comment]
Chris, I don't understand why GitHub doesn't show changes, anything wrong with formatting?

**Comment by chrisknoll** [comment]
Shows it for me:
image

**Comment by alex-odysseus** [comment]
Not on this tab I usually watch https://github.com/OHDSI/WebAPI/pull/2217/files

**Comment by chrisknoll** [comment]
From the link you provided, I see the change:
image

**Comment by chrisknoll** [comment]
Is the problem that you don't know about the 'hide whitespace' option?

image

**Comment by chrisknoll** [comment]
I'd prefer it if we could get review on the material changes on this PR.

**Review by ssuvorov-fls — APPROVED** [review]

**Pull request merged**
