### PR TITLE
SQL Server & Oracle Flyway Patch

### PR DESCRIPTION
**Pull request by anthonysena**
For Oracle/SQL Server, the Flyway script `V2.7.0.20190125113000__fe-analysis-created-modified.sql` created the following columns and foreign key constraints: 

```
ALTER TABLE ${ohdsiSchema}.fe_analysis_criteria ADD created_by_id NUMBER(10) NULL CONSTRAINT FK_fac_su_cid REFERENCES ${ohdsiSchema}.sec_user(id);
ALTER TABLE ${ohdsiSchema}.fe_analysis_criteria ADD modified_by_id NUMBER(10) NULL CONSTRAINT FK_fac_su_mid REFERENCES ${ohdsiSchema}.sec_user(id);
```

Per #782, these columns were created on the wrong table and a patch was issued as part of `V2.7.0.20190129083000__fe-analysis-created-modified-fix.sql`. While attempting to apply this fix in our SQL Server environment, I found that the `fe-analysis-created-modified-fix.sql` script failed to work since we had not dropped the FKs. Furthermore, for SQL Server, I also found that in the original `fe-analysis-created-modified.sql` script did not explicitly name the default constraint which would make creating a patch to drop that default impossible (I presume that SQL Server's column default naming is non-deterministic based on the odd name of: DF__fe_analys_creat__E83F84). 

So, this PR does the following:

- For SQL Server: I've modified the existing scripts `V2.7.0.20190125113000__fe-analysis-created-modified.sql` and `V2.7.0.20190129083000__fe-analysis-created-modified-fix.sql` to use a named default for the column constraint. 
- For both SQL Server & Oracle, I've added in a new script named `V2.7.0.20190129073000__fe-analysis-drop-constraints.sql` which given the flyway naming convention allows it to sit between the two original scripts. This script will drop the FK constraints and for SQL Server, it will also drop the column default constraint.

I attempted to avoid revising existing flyway scripts as discussed in https://github.com/OHDSI/WebAPI/issues/768#issuecomment-457713045 but in this instance I struggled to find a way to safely drop the default since it was not explicitly named originally. 

Please let me know if you have any questions or concerns.

### CODE REVIEW

**Comment by anthonysena** [comment]
@pavgra per our discussion on the ATLAS/WebAPI, could you run this PR on Oracle? @chrisknoll offered to also test this on a fresh instance of Oracle.

**Comment by chrisknoll** [comment]
Actually was going to do this on a fresh instance of SQLServer. I think you tested it where it was an existing instance, but I was concerned that the way the scripts were ordered it may run into an issue on a fresh DB deploy.

I was leaving the Oracle work to @pavgra .

**Comment by anthonysena** [comment]
Thanks @chrisknoll for testing this on SQL Server. Sorry I mixed up the RDBMS in my earlier comment.

**Comment by chrisknoll** [comment]
Ok, for my curent env, I had to rename a default constraint on feature_criteria so that the DROP would work. We knew this hack was necessary, but it is simple and it works.

For the new fresh database (starting from empty db), all tables were created without error!

**Comment by pavgra** [comment]
After some fixes I was finally able to make it working:

```
2019-01-30 19:17:42.917 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.util.VersionPrinter -  - Flyway 4.2.0 by Boxfuse
2019-01-30 19:17:45.935 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.dbsupport.DbSupportFactory -  - Database: jdbc:oracle:thin:@149.56.22.37:1541:orcl (Oracle 11.2)
2019-01-30 19:17:46.445 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.metadatatable.MetaDataTableImpl -  - Creating Metadata table: "TMP"."schema_version"
2019-01-30 19:17:46.985 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Current version of schema "TMP": << Empty Schema >>
2019-01-30 19:17:46.985 WARN RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - outOfOrder mode is active. Migration of schema "TMP" may not be reproducible.
2019-01-30 19:17:46.991 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.1 - schema-create spring batch
2019-01-30 19:17:47.970 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.2 - schema-create jpa
2019-01-30 19:17:48.402 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.3 - cohort definition persistence
2019-01-30 19:17:48.863 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.3.1 - cohort generation
2019-01-30 19:17:49.412 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.3.2 - alter foreign keys
2019-01-30 19:17:49.948 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.4 - cohort analysis results
2019-01-30 19:17:54.960 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.4.1 - heracles heel
2019-01-30 19:17:55.391 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.4.2 - measurement types
2019-01-30 19:17:56.280 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.4.3 - heracles index
2019-01-30 19:17:57.089 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.5 - feasability tables
2019-01-30 19:17:57.787 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.5.1 - alter foreign keys
2019-01-30 19:17:58.304 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.6.1 - schema-create laertes
2019-01-30 19:18:01.373 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.6.2 - schema-create laertes
2019-01-30 19:18:02.298 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.6.3 - schema-create laertes
2019-01-30 19:18:02.740 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.6.4 - schema-create laertes
2019-01-30 19:18:03.617 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.6.5 - schema-create penelope laertes
2019-01-30 19:18:04.069 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.7.0 - sources
2019-01-30 19:18:04.598 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.7.1 - cohort multihomed support
2019-01-30 19:18:05.173 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.7.2 - feasability multihomed support.sql
2019-01-30 19:18:05.780 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.8 - heracles data
2019-01-30 19:18:06.303 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.9 - shiro security
2019-01-30 19:18:08.759 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.0.9.1 - shiro security-initial values
2019-01-30 19:18:10.646 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.1.0 - conceptsets
2019-01-30 19:18:11.474 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.1.1 - penelope
2019-01-30 19:18:12.316 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.1.1.1 - penelope data
2019-01-30 19:20:19.302 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.1.2 - conceptset negative controls
2019-01-30 19:20:19.829 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.1.3 - conceptset generation info
2019-01-30 19:20:20.481 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.2.0 - cohort feasiblity
2019-01-30 19:20:21.069 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.3.1 - comparative cohort analysis
2019-01-30 19:20:21.814 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.4.0 - ir analysis
2019-01-30 19:20:22.510 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.4.1 - ir dist
2019-01-30 19:20:22.929 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.5.0 - rename system user to anonymous
2019-01-30 19:20:23.604 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.6.0 - schema-create-plp
2019-01-30 19:20:24.125 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.6.0.1 - schema-add-analysis execution password
2019-01-30 19:20:25.111 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.7.0 - alter cohort generation info
2019-01-30 19:20:25.902 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.8.0 - cohort features results
2019-01-30 19:20:26.451 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.9.0 - data-permissions
2019-01-30 19:20:29.394 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.10.0 - data-atlas-user
2019-01-30 19:20:29.954 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.11.0 - data-cohortanalysis-permission
2019-01-30 19:20:31.130 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 1.0.11.1 - schema-executions
2019-01-30 19:20:31.657 WARN RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.dbsupport.JdbcTemplate -  - DB: Warning: execution completed with warning (SQL State: 99999 - Error Code: 17110)
2019-01-30 19:20:31.961 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.2.0.20180202143000 - delete-unnecessary-admin-permissions
2019-01-30 19:20:32.416 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.2.0.20180215143000 - remove password
2019-01-30 19:20:33.197 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.2.5.20180212152023 - concept-sets-author
2019-01-30 19:20:33.725 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.2.5.20180212181325 - cca-author
2019-01-30 19:20:34.186 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.2.5.20180215105415 - separate-sequences
2019-01-30 19:20:35.302 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.2.6.20180215152023 - source key unique
2019-01-30 19:20:35.847 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.3.0.20180302143300 - negative control redo
2019-01-30 19:20:36.514 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.3.0.20180302143400 - alter cs gen info
2019-01-30 19:20:37.079 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.3.0.20180330124512 - add source permissions
2019-01-30 19:20:38.236 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.3.0.20180405164306 - add profile permission
2019-01-30 19:20:38.760 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.3.0.20180425185900 - cohort analysis generation info
2019-01-30 19:20:39.440 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.3.0.20180427114800 - sec user unique
2019-01-30 19:20:39.943 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.4.0.20180508090000 - source-credentials
2019-01-30 19:20:40.797 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.4.0.20180516223100 - roles-unique
2019-01-30 19:20:41.292 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.4.3.20180619113700 - permission for my user
2019-01-30 19:20:41.880 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.4.3.20180702202700 - permission for ir execution
2019-01-30 19:20:42.398 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.4.3.20180703144901 - permission for evidence
2019-01-30 19:20:42.953 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.5.0.20180608182403 - schema-add-analysis-gen-progress
2019-01-30 19:20:43.386 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.5.0.20180713123456 - cem v 1
2019-01-30 19:20:44.173 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.5.0.20180720117120 - source-connection-check-rule
2019-01-30 19:20:44.683 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.5.0.20180725172844 - add-ad-import-permissions
2019-01-30 19:20:46.094 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.5.0.20180730192730 - schema-add-kerberos-to-source
2019-01-30 19:20:47.229 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.5.0.20180817154116 - add-extra-import-permissions
2019-01-30 19:20:47.835 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20180731092421 - cohort-characterization
2019-01-30 19:20:54.232 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20180731092422 - cohort-characterization-generations view
2019-01-30 19:20:54.866 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20180906220021 - pathway analysis
2019-01-30 19:20:55.987 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20180910113305 - migrate common entities to user rel
2019-01-30 19:20:58.865 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20180921202400 - fe-analysis-id
2019-01-30 19:20:59.539 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181001200021 - estimation prediction
2019-01-30 19:21:00.720 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181002110845 - fe analysis conceptsets
2019-01-30 19:21:01.087 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181005122300 - schema-create-fe-conceptset
2019-01-30 19:21:02.005 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181008210200 - source-deleted-at-field
2019-01-30 19:21:02.478 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181009110500 - fix-fe-analysis-types
2019-01-30 19:21:02.876 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181009115500 - fix-ple-plp-permissions
2019-01-30 19:21:03.927 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181010133216 - schema-add-job-is-canceled
2019-01-30 19:21:04.945 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181010185036 - schema-user-import-scheduler
2019-01-30 19:21:05.802 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181010185037 - schema-user-import-scheduler-history
2019-01-30 19:21:06.386 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181015182101 - role-group-mapping
2019-01-30 19:21:07.290 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181016171200 - add last viewed notifications time
2019-01-30 19:21:08.156 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181024150353 - separate system personal roles
2019-01-30 19:21:09.510 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181107165252 - fe criteria type
2019-01-30 19:21:10.345 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.6.0.20181128150100 - add missing pk
2019-01-30 19:21:17.683 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.7.0.20181119162154 - cc strata
2019-01-30 19:21:18.668 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.7.0.20190116183005 - default stat type
2019-01-30 19:21:19.309 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.7.0.20190125113000 - fe-analysis-created-modified
2019-01-30 19:21:20.276 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.7.0.20190125141500 - fe-analysis-criteria stat-type-fix
2019-01-30 19:21:21.163 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.7.0.20190129073000 - fe-analysis-drop-constraints
2019-01-30 19:21:21.760 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Migrating schema "TMP" to version 2.7.0.20190129083000 - fe-analysis-created-modified-fix
2019-01-30 19:21:23.450 INFO RMI TCP Connection(5)-127.0.0.1 org.flywaydb.core.internal.command.DbMigrate -  - Successfully applied 88 migrations to schema "TMP" (execution time 03:37.032s).
```

**Pull request merged**
