### PR TITLE
get circe working on oracle

### PR DESCRIPTION
**Pull request by cahilton**
@chrisknoll 

@jduke99 needed Circe to generate in our environment. To get that to work, I had to make these changes. I don't want to break anything, but doesn't work in Oracle without the target schema being used.

Thanks.

### CODE REVIEW

**Comment by chrisknoll** [comment]
Charity:
See this post about the new property that was added to pom.xml
http://forums.ohdsi.org/t/circe-generate/431/3?u=chris_knoll

**Comment by cahilton** [comment]
ok - I can specify the pom property for now, but it might be cleaner eventually to just used ohdsi_schema + cohort, since  I think we've moved towards that with Heracles.

Trying session id now.

**Comment by cahilton** [comment]
Also that new translate method requires the oracleTempTable schema (which for us is the OHDSI schema), but going to try null for now.

**Comment by cahilton** [comment]
Okay, the changes I have in this branch now work.

So, I added the schema name + cohort name in the oracle profile, and I passed in the session id on the generate cohort tasklet

**Comment by chrisknoll** [comment]
Perfect. I'll draft up a pull request to remove cohort.targetTable property from being required.  Great work.

**Pull request merged**
