### PR TITLE
Issue 1979 add spark support

### LINKED ISSUE #1979: Add Spark support
Add support for Spark DBMS type.

### PR DESCRIPTION
**Pull request by anton-abushkevich**
Resolves #1979

### CODE REVIEW

**Review by chrisknoll — DISMISSED** [review]

**Comment by chrisknoll** [comment]
https://github.com/OHDSI/WebAPI/runs/5192960528?check_suite_focus=true

The build failed trying to resolve a dependency.

**Comment by chrisknoll** [comment]
I'm adjusting the pom in SkelCohortChar to remove that old URL, so you may want to change this to reference SCC version 1.2.1 instead of making an exclusion in the pom.xml. I'm not sure what sort of issues excluding the artifacts may cause down the line...

**Comment by anton-abushkevich** [comment]
@chrisknoll 
OK. Please, publish SCC 1.2.1 in ohdsi repo:
```Could not find artifact org.ohdsi:SkeletonCohortCharacterization:pom:1.2.1 in ohdsi (https://repo.ohdsi.org/nexus/content/groups/public)```

**Comment by chrisknoll** [comment]
Ok, I see that 1.2.1 is now available on the OHDSI nexus repo. Can you try to build again?

**Review by chrisknoll — APPROVED** [review]
Note: other PRs are modifying dependencies, so we should expect to see conflicts, but they should be very simple to resolve.

**Pull request merged**
